$ErrorActionPreference = 'Stop'
# Machine-translated marketing copy. The captured app interface remains English.
# Fields: locale | App Store name | tagline | four title/subtitle pairs | footer.
$rows = @'
en-GB|English (U.K.)|Plumbing training game|Plumbing Training Game|Practise leaks, blocked drains and water pressure faults.|Practise Fault Diagnosis|Read symptoms and choose a plumbing diagnosis.|Learn Plumbing Tools|Build your kit for pipe, drain and heating scenarios.|Plumbing Repair Simulation|Choose a repair and learn from job feedback.|Educational simulation. App interface in English.
en-AU|English (Australia)|Plumbing training game|Plumbing Training Game|Practise leaks, blocked drains and water pressure faults.|Practise Fault Diagnosis|Read symptoms and choose a plumbing diagnosis.|Learn Plumbing Tools|Build your kit for pipe, drain and heating scenarios.|Plumbing Repair Simulation|Choose a repair and learn from job feedback.|Educational simulation. App interface in English.
en-CA|English (Canada)|Plumbing training game|Plumbing Training Game|Practise leaks, blocked drains and water pressure faults.|Practise Fault Diagnosis|Read symptoms and choose a plumbing diagnosis.|Learn Plumbing Tools|Build your kit for pipe, drain and heating scenarios.|Plumbing Repair Simulation|Choose a repair and learn from job feedback.|Educational simulation. App interface in English.
en-US|English (U.S.)|Plumbing training game|Plumbing Training Game|Practice leaks, blocked drains and water pressure faults.|Practice Fault Diagnosis|Read symptoms and choose a plumbing diagnosis.|Learn Plumbing Tools|Build your kit for pipe, drain and heating scenarios.|Plumbing Repair Simulation|Choose a repair and learn from job feedback.|Educational simulation. App interface in English.
ar-SA|Arabic|لعبة تدريب على السباكة|تعلّم السباكة باللعب|تدرّب على التسربات وانسداد المصارف وأعطال ضغط المياه.|تدرّب على تشخيص الأعطال|اقرأ الأعراض واختر تشخيص عطل السباكة.|تعرّف على أدوات السباكة|جهّز أدواتك لمهام الأنابيب والصرف والتدفئة.|محاكاة إصلاح السباكة|اختر الإصلاح وتعلّم من ملاحظات كل مهمة.|محاكاة تعليمية. واجهة التطبيق باللغة الإنجليزية.
bn|Bangla|প্লাম্বিং শেখার খেলা|খেলে প্লাম্বিং শিখুন|লিক, বন্ধ ড্রেন ও পানির চাপের সমস্যা নিয়ে অনুশীলন করুন।|ত্রুটি নির্ণয়ের অনুশীলন|লক্ষণ পড়ে প্লাম্বিং সমস্যার কারণ বেছে নিন।|প্লাম্বিংয়ের সরঞ্জাম শিখুন|পাইপ, ড্রেন ও হিটিংয়ের কাজের জন্য সরঞ্জাম সংগ্রহ করুন।|প্লাম্বিং মেরামতের সিমুলেশন|মেরামত বেছে নিন ও কাজের ফলাফল থেকে শিখুন।|শিক্ষামূলক সিমুলেশন। অ্যাপের ইন্টারফেস ইংরেজিতে।
ca|Catalan|Joc de formació en fontaneria|Aprèn fontaneria jugant|Practica amb fuites, desguassos obstruïts i problemes de pressió.|Practica el diagnòstic|Llegeix els símptomes i tria un diagnòstic de fontaneria.|Coneix les eines de fontaneria|Prepara les eines per a canonades, desguassos i calefacció.|Simula reparacions|Tria una reparació i aprèn amb els comentaris de cada feina.|Simulació educativa. Interfície de l’app en anglès.
zh-Hans|Chinese (Simplified)|水暖技能训练游戏|在游戏中学习水暖技能|练习处理漏水、排水堵塞和水压故障。|练习故障诊断|阅读症状并选择水暖故障诊断。|认识水暖工具|为管道、排水和供暖任务准备工具。|模拟水暖维修|选择维修方案，从任务反馈中学习。|教育模拟。应用界面为英语。
zh-Hant|Chinese (Traditional)|水電技能訓練遊戲|在遊戲中學習水電技能|練習處理漏水、排水堵塞和水壓故障。|練習故障診斷|閱讀症狀並選擇水電故障診斷。|認識水電工具|為管線、排水和供暖任務準備工具。|模擬水電維修|選擇維修方案，從任務回饋中學習。|教育模擬。應用程式介面為英語。
hr|Croatian|Igra za učenje vodoinstalacija|Učite vodoinstalacije|Vježbajte curenja, začepljene odvode i probleme s tlakom vode.|Vježbajte dijagnostiku|Pročitajte simptome i odaberite uzrok kvara.|Upoznajte vodoinstalaterski alat|Pripremite alat za cijevi, odvode i grijanje.|Simulirajte popravke|Odaberite popravak i učite iz povratnih informacija.|Edukativna simulacija. Sučelje aplikacije je na engleskom.
cs|Czech|Výuková instalatérská hra|Učte se instalatérství|Procvičujte úniky vody, ucpané odpady a poruchy tlaku.|Procvičte diagnostiku|Přečtěte příznaky a vyberte příčinu závady.|Poznejte instalatérské nářadí|Sestavte výbavu pro potrubí, odpady a topení.|Simulujte opravy|Vyberte opravu a učte se ze zpětné vazby.|Výuková simulace. Rozhraní aplikace je v angličtině.
da|Danish|Træningsspil om VVS|Lær VVS gennem spil|Øv dig på lækager, tilstoppede afløb og vandtryksfejl.|Øv fejldiagnose|Læs symptomerne, og vælg en VVS-diagnose.|Lær VVS-værktøjerne|Saml værktøj til rør, afløb og varmeopgaver.|Simuler VVS-reparationer|Vælg en reparation, og lær af opgavens feedback.|Læringssimulation. Appens brugerflade er på engelsk.
nl-NL|Dutch|Trainingsspel voor loodgieters|Leer loodgieterswerk|Oefen met lekkages, verstopte afvoeren en waterdrukproblemen.|Oefen storingsdiagnose|Lees de symptomen en kies een diagnose.|Leer loodgietersgereedschap|Bouw je uitrusting voor leidingen, afvoer en verwarming.|Simuleer reparaties|Kies een reparatie en leer van de feedback.|Educatieve simulatie. De app-interface is in het Engels.
fi|Finnish|Putkityön harjoittelupeli|Opi putkitöitä pelaamalla|Harjoittele vuotoja, tukoksia ja vedenpaineen häiriöitä.|Harjoittele vianmääritystä|Lue oireet ja valitse putkivian diagnoosi.|Tutustu putkityökaluihin|Kokoa työkalut putki-, viemäri- ja lämmitystehtäviin.|Simuloi putkikorjauksia|Valitse korjaus ja opi tehtävän palautteesta.|Opetussimulaatio. Sovelluksen käyttöliittymä on englanniksi.
fr-FR|French|Jeu de formation en plomberie|Apprenez la plomberie|Entraînez-vous sur les fuites, drains bouchés et problèmes de pression.|Exercez le diagnostic|Lisez les symptômes et choisissez un diagnostic de plomberie.|Découvrez les outils|Préparez votre équipement pour tuyaux, drains et chauffage.|Simulez les réparations|Choisissez une réparation et apprenez grâce aux retours.|Simulation éducative. Interface de l’application en anglais.
fr-CA|French (Canada)|Jeu de formation en plomberie|Apprenez la plomberie|Exercez-vous sur les fuites, drains bouchés et problèmes de pression.|Exercez le diagnostic|Lisez les symptômes et choisissez un diagnostic de plomberie.|Découvrez les outils|Préparez votre équipement pour tuyaux, drains et chauffage.|Simulez les réparations|Choisissez une réparation et apprenez grâce aux commentaires.|Simulation éducative. Interface de l’application en anglais.
de-DE|German|Lernspiel für Sanitärtechnik|Sanitärtechnik lernen|Übe Lecks, verstopfte Abflüsse und Wasserdruckprobleme.|Fehlerdiagnose üben|Lies die Symptome und wähle eine Fehlerdiagnose.|Werkzeuge kennenlernen|Stelle dein Werkzeug für Rohre, Abflüsse und Heizung zusammen.|Reparaturen simulieren|Wähle eine Reparatur und lerne aus dem Feedback.|Lernsimulation. Die App-Oberfläche ist auf Englisch.
el|Greek|Παιχνίδι εκπαίδευσης υδραυλικών|Μάθε υδραυλικές εργασίες|Εξασκήσου σε διαρροές, βουλωμένες αποχετεύσεις και προβλήματα πίεσης.|Εξασκήσου στη διάγνωση|Διάβασε τα συμπτώματα και επίλεξε διάγνωση βλάβης.|Γνώρισε τα εργαλεία|Φτιάξε το σετ σου για σωλήνες, αποχετεύσεις και θέρμανση.|Προσομοίωσε επισκευές|Επίλεξε επισκευή και μάθε από την ανατροφοδότηση.|Εκπαιδευτική προσομοίωση. Η εφαρμογή έχει αγγλικό περιβάλλον.
gu|Gujarati|પ્લમ્બિંગ શીખવાની રમત|રમત દ્વારા પ્લમ્બિંગ શીખો|લીક, બંધ ડ્રેન અને પાણીના દબાણની ખામીનો અભ્યાસ કરો.|ખામીનું નિદાન શીખો|લક્ષણો વાંચો અને પ્લમ્બિંગની ખામીનું નિદાન પસંદ કરો.|પ્લમ્બિંગનાં સાધનો જાણો|પાઇપ, ડ્રેન અને હીટિંગનાં કામ માટે સાધનો ભેગાં કરો.|પ્લમ્બિંગ રિપેર સિમ્યુલેશન|રિપેર પસંદ કરો અને કામના પ્રતિસાદમાંથી શીખો.|શૈક્ષણિક સિમ્યુલેશન. ઍપનું ઇન્ટરફેસ અંગ્રેજીમાં છે.
he|Hebrew|משחק ללימוד אינסטלציה|למדו אינסטלציה במשחק|תרגלו נזילות, סתימות ובעיות בלחץ המים.|תרגלו אבחון תקלות|קראו את התסמינים ובחרו אבחון לתקלה.|הכירו כלי אינסטלציה|הרכיבו ערכת כלים לצינורות, ניקוז וחימום.|סימולציית תיקונים|בחרו תיקון ולמדו מהמשוב על העבודה.|סימולציה לימודית. ממשק האפליקציה באנגלית.
hi|Hindi|प्लंबिंग सीखने का खेल|खेलकर प्लंबिंग सीखें|रिसाव, बंद नालियों और पानी के दबाव की समस्याओं का अभ्यास करें।|खराबी पहचानने का अभ्यास|लक्षण पढ़ें और प्लंबिंग की खराबी का कारण चुनें।|प्लंबिंग के औज़ार सीखें|पाइप, नाली और हीटिंग के काम के लिए औज़ार जुटाएँ।|प्लंबिंग मरम्मत सिमुलेशन|मरम्मत चुनें और काम की प्रतिक्रिया से सीखें।|शैक्षिक सिमुलेशन। ऐप का इंटरफ़ेस अंग्रेज़ी में है।
hu|Hungarian|Vízvezeték-szerelési oktatójáték|Tanulj vízvezeték-szerelést|Gyakorolj szivárgásokat, dugulásokat és víznyomáshibákat.|Gyakorold a hibafeltárást|Olvasd el a tüneteket, és válassz diagnózist.|Ismerd meg a szerszámokat|Állítsd össze eszközeidet cső-, lefolyó- és fűtési munkákhoz.|Szimulálj javításokat|Válassz javítást, és tanulj a visszajelzésből.|Oktatási szimuláció. Az alkalmazás felülete angol nyelvű.
id|Indonesian|Game latihan perpipaan|Belajar perpipaan lewat game|Latih kebocoran, saluran tersumbat dan masalah tekanan air.|Latih diagnosis kerusakan|Baca gejala dan pilih diagnosis masalah perpipaan.|Kenali alat perpipaan|Siapkan alat untuk pipa, saluran air dan pemanas.|Simulasi perbaikan pipa|Pilih perbaikan dan pelajari umpan balik tugas.|Simulasi edukasi. Antarmuka aplikasi berbahasa Inggris.
it|Italian|Gioco di formazione idraulica|Impara l’idraulica giocando|Esercitati su perdite, scarichi ostruiti e problemi di pressione.|Esercita la diagnosi|Leggi i sintomi e scegli una diagnosi idraulica.|Scopri gli attrezzi idraulici|Prepara il kit per tubi, scarichi e riscaldamento.|Simula le riparazioni|Scegli una riparazione e impara dai riscontri.|Simulazione educativa. Interfaccia dell’app in inglese.
ja|Japanese|配管トレーニングゲーム|ゲームで配管を学ぼう|水漏れ、排水の詰まり、水圧の問題に取り組もう。|故障診断を練習|症状を読んで配管の故障原因を選ぼう。|配管工具を学ぼう|配管・排水・暖房の課題に使う工具を揃えよう。|配管修理シミュレーション|修理方法を選び、結果のフィードバックから学ぼう。|学習用シミュレーション。アプリの操作画面は英語です。
kn|Kannada|ಪ್ಲಂಬಿಂಗ್ ಕಲಿಕೆಯ ಆಟ|ಆಟದ ಮೂಲಕ ಪ್ಲಂಬಿಂಗ್ ಕಲಿಯಿರಿ|ಸೋರಿಕೆ, ಮುಚ್ಚಿದ ಚರಂಡಿ ಮತ್ತು ನೀರಿನ ಒತ್ತಡದ ದೋಷಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ.|ದೋಷ ಪತ್ತೆ ಅಭ್ಯಾಸ|ಲಕ್ಷಣಗಳನ್ನು ಓದಿ ಪ್ಲಂಬಿಂಗ್ ದೋಷದ ಕಾರಣ ಆರಿಸಿ.|ಪ್ಲಂಬಿಂಗ್ ಉಪಕರಣ ತಿಳಿಯಿರಿ|ಪೈಪ್, ಚರಂಡಿ ಮತ್ತು ತಾಪನ ಕಾರ್ಯಗಳಿಗೆ ಉಪಕರಣ ಸಂಗ್ರಹಿಸಿ.|ಪ್ಲಂಬಿಂಗ್ ದುರಸ್ತಿ ಸಿಮ್ಯುಲೇಶನ್|ದುರಸ್ತಿ ಆರಿಸಿ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಯಿಂದ ಕಲಿಯಿರಿ.|ಶೈಕ್ಷಣಿಕ ಸಿಮ್ಯುಲೇಶನ್. ಆ್ಯಪ್ ಇಂಟರ್‌ಫೇಸ್ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿದೆ.
ko|Korean|배관 기술 학습 게임|게임으로 배관 배우기|누수, 배수구 막힘, 수압 문제를 연습하세요.|고장 진단 연습|증상을 읽고 배관 고장 진단을 선택하세요.|배관 공구 배우기|배관, 배수, 난방 작업에 필요한 공구를 모으세요.|배관 수리 시뮬레이션|수리 방법을 선택하고 작업 피드백으로 배우세요.|교육용 시뮬레이션. 앱 인터페이스는 영어입니다.
ms|Malay|Permainan latihan paip|Belajar kerja paip|Latih kebocoran, saliran tersumbat dan masalah tekanan air.|Latih diagnosis kerosakan|Baca gejala dan pilih diagnosis masalah paip.|Kenali alat kerja paip|Sediakan alat untuk paip, saliran dan pemanasan.|Simulasi pembaikan paip|Pilih pembaikan dan belajar daripada maklum balas.|Simulasi pendidikan. Antara muka aplikasi dalam bahasa Inggeris.
ml|Malayalam|പ്ലംബിംഗ് പഠന ഗെയിം|കളിച്ച് പ്ലംബിംഗ് പഠിക്കൂ|ചോർച്ച, അടഞ്ഞ ഡ്രെയിൻ, ജലമർദ്ദ തകരാർ എന്നിവ പരിശീലിക്കൂ.|തകരാർ കണ്ടെത്താൻ പരിശീലിക്കൂ|ലക്ഷണങ്ങൾ വായിച്ച് പ്ലംബിംഗ് തകരാറിന്റെ കാരണം തിരഞ്ഞെടുക്കൂ.|പ്ലംബിംഗ് ഉപകരണങ്ങൾ പഠിക്കൂ|പൈപ്പ്, ഡ്രെയിൻ, ഹീറ്റിംഗ് ജോലികൾക്കുള്ള ഉപകരണങ്ങൾ ശേഖരിക്കൂ.|പ്ലംബിംഗ് റിപ്പയർ സിമുലേഷൻ|അറ്റകുറ്റപ്പണി തിരഞ്ഞെടുത്ത് പ്രതികരണത്തിൽ നിന്ന് പഠിക്കൂ.|വിദ്യാഭ്യാസ സിമുലേഷൻ. ആപ്പിന്റെ ഇന്റർഫേസ് ഇംഗ്ലീഷിലാണ്.
mr|Marathi|प्लंबिंग शिकण्याचा खेळ|खेळातून प्लंबिंग शिका|गळती, बंद नाले आणि पाण्याच्या दाबातील बिघाडाचा सराव करा.|बिघाड शोधण्याचा सराव|लक्षणे वाचा आणि प्लंबिंगच्या बिघाडाचे कारण निवडा.|प्लंबिंगची साधने ओळखा|पाइप, नाले आणि हीटिंगच्या कामांसाठी साधने गोळा करा.|प्लंबिंग दुरुस्ती सिम्युलेशन|दुरुस्ती निवडा आणि कामाच्या अभिप्रायातून शिका.|शैक्षणिक सिम्युलेशन. ॲपचा इंटरफेस इंग्रजीत आहे.
no|Norwegian|Treningsspill for rørleggere|Lær rørleggerarbeid|Øv på lekkasjer, tette avløp og problemer med vanntrykk.|Øv på feildiagnose|Les symptomene og velg en diagnose.|Lær om rørleggerverktøy|Samle verktøy for rør, avløp og varmeoppgaver.|Simuler rørreparasjoner|Velg en reparasjon og lær av tilbakemeldingen.|Læringssimulering. Appens grensesnitt er på engelsk.
or|Odia|ପ୍ଲମ୍ବିଂ ଶିକ୍ଷା ଖେଳ|ଖେଳି ପ୍ଲମ୍ବିଂ ଶିଖନ୍ତୁ|ଲିକ୍, ବନ୍ଦ ଡ୍ରେନ୍ ଓ ଜଳଚାପ ତ୍ରୁଟିର ଅଭ୍ୟାସ କରନ୍ତୁ।|ତ୍ରୁଟି ଚିହ୍ନଟ ଅଭ୍ୟାସ|ଲକ୍ଷଣ ପଢ଼ି ପ୍ଲମ୍ବିଂ ତ୍ରୁଟିର କାରଣ ବାଛନ୍ତୁ।|ପ୍ଲମ୍ବିଂ ଉପକରଣ ଜାଣନ୍ତୁ|ପାଇପ୍, ଡ୍ରେନ୍ ଓ ହିଟିଂ କାମ ପାଇଁ ଉପକରଣ ସଂଗ୍ରହ କରନ୍ତୁ।|ପ୍ଲମ୍ବିଂ ମରାମତି ସିମୁଲେସନ୍|ମରାମତି ବାଛି କାମର ମତାମତରୁ ଶିଖନ୍ତୁ।|ଶିକ୍ଷାମୂଳକ ସିମୁଲେସନ୍। ଆପ୍ ଇଣ୍ଟରଫେସ୍ ଇଂରାଜୀରେ ଅଛି।
pl|Polish|Gra do nauki hydrauliki|Ucz się hydrauliki w grze|Ćwicz wycieki, zatkane odpływy i problemy z ciśnieniem.|Ćwicz diagnozowanie usterek|Przeczytaj objawy i wybierz diagnozę.|Poznaj narzędzia hydrauliczne|Zbierz narzędzia do rur, odpływów i ogrzewania.|Symuluj naprawy|Wybierz naprawę i ucz się z informacji zwrotnej.|Symulacja edukacyjna. Interfejs aplikacji jest po angielsku.
pt-BR|Portuguese (Brazil)|Jogo de treinamento hidráulico|Aprenda hidráulica jogando|Pratique vazamentos, ralos entupidos e problemas de pressão.|Pratique o diagnóstico|Leia os sintomas e escolha um diagnóstico hidráulico.|Conheça as ferramentas|Monte seu kit para tubos, drenagem e aquecimento.|Simule reparos hidráulicos|Escolha um reparo e aprenda com o feedback.|Simulação educativa. Interface do app em inglês.
pt-PT|Portuguese (Portugal)|Jogo de formação em canalização|Aprenda canalização|Pratique fugas, esgotos entupidos e problemas de pressão.|Pratique o diagnóstico|Leia os sintomas e escolha um diagnóstico de canalização.|Conheça as ferramentas|Prepare o kit para tubos, esgotos e aquecimento.|Simule reparações|Escolha uma reparação e aprenda com os comentários.|Simulação educativa. Interface da aplicação em inglês.
pa|Punjabi|ਪਲੰਬਿੰਗ ਸਿੱਖਣ ਦੀ ਖੇਡ|ਖੇਡ ਕੇ ਪਲੰਬਿੰਗ ਸਿੱਖੋ|ਲੀਕ, ਬੰਦ ਨਾਲੀਆਂ ਅਤੇ ਪਾਣੀ ਦੇ ਦਬਾਅ ਦੀਆਂ ਖ਼ਰਾਬੀਆਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।|ਖ਼ਰਾਬੀ ਪਛਾਣਨ ਦਾ ਅਭਿਆਸ|ਲੱਛਣ ਪੜ੍ਹੋ ਅਤੇ ਪਲੰਬਿੰਗ ਦੀ ਖ਼ਰਾਬੀ ਦਾ ਕਾਰਨ ਚੁਣੋ।|ਪਲੰਬਿੰਗ ਦੇ ਔਜ਼ਾਰ ਜਾਣੋ|ਪਾਈਪ, ਨਾਲੀ ਅਤੇ ਹੀਟਿੰਗ ਦੇ ਕੰਮ ਲਈ ਔਜ਼ਾਰ ਇਕੱਠੇ ਕਰੋ।|ਪਲੰਬਿੰਗ ਮੁਰੰਮਤ ਸਿਮੂਲੇਸ਼ਨ|ਮੁਰੰਮਤ ਚੁਣੋ ਅਤੇ ਕੰਮ ਦੇ ਫੀਡਬੈਕ ਤੋਂ ਸਿੱਖੋ।|ਸਿੱਖਿਆ ਲਈ ਸਿਮੂਲੇਸ਼ਨ। ਐਪ ਦਾ ਇੰਟਰਫੇਸ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਹੈ।
ro|Romanian|Joc de instruire în instalații|Învață lucrări de instalații|Exersează scurgeri, canale înfundate și probleme de presiune.|Exersează diagnosticarea|Citește simptomele și alege diagnosticul defecțiunii.|Cunoaște uneltele|Pregătește trusa pentru țevi, scurgeri și încălzire.|Simulează reparații|Alege reparația și învață din feedback.|Simulare educativă. Interfața aplicației este în engleză.
ru|Russian|Игра для обучения сантехнике|Изучайте сантехнику в игре|Тренируйтесь устранять протечки, засоры и проблемы давления.|Практикуйте диагностику|Прочитайте симптомы и выберите причину неисправности.|Изучайте инструменты|Соберите инструменты для труб, сливов и отопления.|Симуляция ремонта|Выберите ремонт и учитесь по результатам задания.|Учебная симуляция. Интерфейс приложения на английском.
sk|Slovak|Inštalatérska vzdelávacia hra|Učte sa inštalatérstvo|Precvičujte úniky vody, upchaté odpady a poruchy tlaku.|Precvičte diagnostiku|Prečítajte príznaky a vyberte príčinu poruchy.|Spoznajte inštalatérske náradie|Zostavte výbavu pre potrubia, odpady a kúrenie.|Simulujte opravy|Vyberte opravu a učte sa zo spätnej väzby.|Vzdelávacia simulácia. Rozhranie aplikácie je v angličtine.
sl|Slovenian|Igra za učenje vodovodnih del|Učite se vodovodnih del|Vadite puščanje, zamašene odtoke in težave s tlakom vode.|Vadite diagnozo napak|Preberite simptome in izberite vzrok napake.|Spoznajte vodovodna orodja|Pripravite orodje za cevi, odtoke in ogrevanje.|Simulirajte popravila|Izberite popravilo in se učite iz povratnih informacij.|Izobraževalna simulacija. Vmesnik aplikacije je v angleščini.
es-MX|Spanish (Mexico)|Juego de capacitación en plomería|Aprende plomería jugando|Practica fugas, desagües tapados y problemas de presión.|Practica el diagnóstico|Lee los síntomas y elige un diagnóstico de plomería.|Conoce las herramientas|Prepara tu equipo para tuberías, desagües y calefacción.|Simula reparaciones|Elige una reparación y aprende con los comentarios.|Simulación educativa. Interfaz de la app en inglés.
es-ES|Spanish (Spain)|Juego de formación en fontanería|Aprende fontanería jugando|Practica fugas, desagües atascados y problemas de presión.|Practica el diagnóstico|Lee los síntomas y elige un diagnóstico de fontanería.|Conoce las herramientas|Prepara tu equipo para tuberías, desagües y calefacción.|Simula reparaciones|Elige una reparación y aprende con los comentarios.|Simulación educativa. Interfaz de la aplicación en inglés.
sv|Swedish|Träningsspel för VVS|Lär dig VVS genom spel|Öva på läckor, igensatta avlopp och problem med vattentryck.|Öva på feldiagnos|Läs symtomen och välj en VVS-diagnos.|Lär känna VVS-verktygen|Samla verktyg för rör, avlopp och värmeuppgifter.|Simulera reparationer|Välj en reparation och lär av återkopplingen.|Utbildningssimulering. Appens gränssnitt är på engelska.
ta|Tamil|பிளம்பிங் பயிற்சி விளையாட்டு|விளையாடி பிளம்பிங் கற்கவும்|கசிவுகள், அடைத்த வடிகால்கள், நீர் அழுத்தக் கோளாறுகளைப் பயிற்சி செய்யவும்.|கோளாறு கண்டறியும் பயிற்சி|அறிகுறிகளைப் படித்து பிளம்பிங் கோளாறின் காரணத்தைத் தேர்வுசெய்யவும்.|பிளம்பிங் கருவிகளை அறியவும்|குழாய், வடிகால், வெப்பமூட்டும் பணிகளுக்குக் கருவிகளைச் சேகரிக்கவும்.|பிளம்பிங் பழுது சிமுலேஷன்|பழுதுபார்ப்பைத் தேர்வுசெய்து கருத்துகளிலிருந்து கற்கவும்.|கல்விக்கான சிமுலேஷன். செயலியின் இடைமுகம் ஆங்கிலத்தில் உள்ளது.
te|Telugu|ప్లంబింగ్ శిక్షణ ఆట|ఆడుతూ ప్లంబింగ్ నేర్చుకోండి|లీకులు, మూసుకుపోయిన డ్రెయిన్‌లు, నీటి ఒత్తిడి లోపాలను సాధన చేయండి.|లోప నిర్ధారణ సాధన|లక్షణాలను చదివి ప్లంబింగ్ లోపానికి కారణం ఎంచుకోండి.|ప్లంబింగ్ పనిముట్లు తెలుసుకోండి|పైపు, డ్రెయిన్, హీటింగ్ పనులకు పనిముట్లు సేకరించండి.|ప్లంబింగ్ మరమ్మతు సిమ్యులేషన్|మరమ్మతు ఎంచుకుని పని అభిప్రాయం నుంచి నేర్చుకోండి.|విద్యా సిమ్యులేషన్. యాప్ ఇంటర్‌ఫేస్ ఆంగ్లంలో ఉంది.
th|Thai|เกมฝึกทักษะงานประปา|เรียนรู้งานประปาผ่านเกม|ฝึกแก้ปัญหาน้ำรั่ว ท่อระบายน้ำอุดตัน และแรงดันน้ำผิดปกติ|ฝึกวินิจฉัยปัญหา|อ่านอาการและเลือกสาเหตุของปัญหางานประปา|เรียนรู้เครื่องมืองานประปา|รวบรวมเครื่องมือสำหรับท่อ ระบบระบายน้ำ และระบบทำความร้อน|จำลองการซ่อมประปา|เลือกวิธีซ่อมและเรียนรู้จากผลตอบรับของงาน|การจำลองเพื่อการศึกษา อินเทอร์เฟซแอปเป็นภาษาอังกฤษ
tr|Turkish|Tesisat eğitimi oyunu|Oyunla tesisat öğrenin|Sızıntı, tıkalı gider ve su basıncı sorunları üzerinde çalışın.|Arıza teşhisini çalışın|Belirtileri okuyun ve bir tesisat teşhisi seçin.|Tesisat aletlerini tanıyın|Boru, gider ve ısıtma işleri için aletlerinizi toplayın.|Onarımları simüle edin|Onarım seçin ve iş geri bildiriminden öğrenin.|Eğitim simülasyonu. Uygulama arayüzü İngilizcedir.
uk|Ukrainian|Гра для навчання сантехніки|Вивчайте сантехніку у грі|Тренуйтеся на протіканнях, засміченнях і проблемах тиску.|Практикуйте діагностику|Прочитайте симптоми й оберіть причину несправності.|Вивчайте інструменти|Зберіть інструменти для труб, зливів і опалення.|Симуляція ремонту|Оберіть ремонт і навчайтеся за відгуками про завдання.|Навчальна симуляція. Інтерфейс застосунку англійською.
ur|Urdu|پلمبنگ سیکھنے کا کھیل|کھیل کر پلمبنگ سیکھیں|رساؤ، بند نالیوں اور پانی کے دباؤ کی خرابیوں کی مشق کریں۔|خرابی کی تشخیص کی مشق|علامات پڑھیں اور پلمبنگ کی خرابی کی وجہ منتخب کریں۔|پلمبنگ کے اوزار جانیں|پائپ، نکاسی اور ہیٹنگ کے کام کے لیے اوزار جمع کریں۔|پلمبنگ مرمت کی سیمولیشن|مرمت منتخب کریں اور کام کے نتائج سے سیکھیں۔|تعلیمی سیمولیشن۔ ایپ کا انٹرفیس انگریزی میں ہے۔
vi|Vietnamese|Trò chơi học nghề sửa ống nước|Học sửa ống nước qua trò chơi|Luyện xử lý rò rỉ, tắc đường thoát nước và lỗi áp lực nước.|Luyện chẩn đoán sự cố|Đọc triệu chứng và chọn nguyên nhân sự cố đường ống.|Tìm hiểu dụng cụ|Chuẩn bị bộ dụng cụ cho ống, thoát nước và sưởi.|Mô phỏng sửa ống nước|Chọn cách sửa và học từ phản hồi công việc.|Mô phỏng giáo dục. Giao diện ứng dụng bằng tiếng Anh.
'@
$result = [ordered]@{}
foreach ($row in ($rows -split '\r?\n')) {
    $fields = $row.Split('|')
    if ($fields.Count -ne 12) { throw "Invalid row: $($fields[0]) ($($fields.Count) fields)" }
    $shots = @(for ($i = 0; $i -lt 4; $i++) { @{title=$fields[3 + 2 * $i]; subtitle=$fields[4 + 2 * $i]} })
    $result[$fields[0]] = @{name=$fields[1]; tagline=$fields[2]; shots=$shots; footer=$fields[11]; rtl=($fields[0] -in @('ar-SA','he','ur'))}
}
$output = Join-Path $PSScriptRoot 'duo-captions.json'
$result | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $output -Encoding utf8
Write-Output "Saved $($result.Count) locale caption sets to $output"
